import { ITEM_TYPES } from "./room";
//两室一厅
export const LAYOUT1_TW = {
    canvasPosition: { x: 0, y: -18 },
    compassRotation: 0,
    scale: 61,
    localItems: [
        {
            id: "bathroom-1",
            type: ITEM_TYPES.ROOM,
            data: {
                cateType: ITEM_TYPES.ROOM,
                type: "bathroom",
                label: "浴室1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/room-icon/bathroom.png",
                size: { width: 300, height: 300 },
            },
            size: { width: 300, height: 300 },
            position: { x: 284.47058823529414, y: 329.37254901960785 },
            rotation: 0,
        },
        {
            id: "dining_room-1",
            type: ITEM_TYPES.ROOM,
            data: {
                cateType: ITEM_TYPES.ROOM,
                type: "dining_room",
                label: "飯廳1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/room-icon/dining_room.png",
                size: { width: 300, height: 300 },
            },
            size: { width: 441, height: 296 },
            position: { x: 144.84313725490188, y: 632.8823529411765 },
            rotation: 0,
        },
        {
            id: "living_room-1",
            type: ITEM_TYPES.ROOM,
            data: {
                cateType: ITEM_TYPES.ROOM,
                type: "living_room",
                label: "客廳1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/room-icon/living_room.png",
                size: { width: 300, height: 300 },
            },
            size: { width: 443, height: 290 },
            position: { x: 588.1176470588235, y: 634.4509803921569 },
            rotation: 0,
        },
        {
            id: "bedroom-1",
            type: ITEM_TYPES.ROOM,
            data: {
                cateType: ITEM_TYPES.ROOM,
                type: "bedroom",
                label: "睡房1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/room-icon/bedroom.png",
                size: { width: 300, height: 300 },
            },
            size: { width: 367, height: 304 },
            position: { x: 589.5882352941177, y: 330.78431372549016 },
            rotation: 0,
        },
        {
            id: "bedroom-2",
            type: ITEM_TYPES.ROOM,
            data: {
                cateType: ITEM_TYPES.ROOM,
                type: "bedroom",
                label: "睡房2",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/room-icon/bedroom.png",
                size: { width: 300, height: 300 },
            },
            size: { width: 421, height: 375 },
            position: { x: 593.3529411764706, y: 926.4705882352941 },
            rotation: 0,
        },
        {
            id: "kitchen-1",
            type: ITEM_TYPES.ROOM,
            data: {
                cateType: ITEM_TYPES.ROOM,
                type: "kitchen",
                label: "廚房1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/room-icon/kitchen.png",
                size: { width: 300, height: 300 },
            },
            size: { width: 270, height: 363 },
            position: { x: 315.0392156862745, y: 930.4509803921569 },
            rotation: 0,
        },
        {
            id: "balcony-1",
            type: ITEM_TYPES.ROOM,
            data: {
                cateType: ITEM_TYPES.ROOM,
                type: "balcony",
                label: "陽台1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/room-icon/balcony.png",
                size: { width: 300, height: 300 },
            },
            size: { width: 116, height: 296 },
            position: { x: 1030.764705882353, y: 635.8039215686274 },
            rotation: 0,
        },
        // --- Furniture ---
        {
            id: "toilet-1",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/toilet-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "toilet",
                label: "浴室1-馬桶1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/toilet.png",
                size: { width: 40, height: 60 },
            },
            size: { width: 40, height: 60 },
            position: { x: 410.843137254902, y: 351.5490196078431 },
            rotation: 0,
            parentId: null,
            offset: { x: 134.843137254902, y: 7.549019607843093 },
        },
        {
            id: "shower-1",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/shower-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "shower",
                label: "浴室1-淋浴1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/shower.png",
                size: { width: 80, height: 80 },
            },
            size: { width: 80, height: 80 },
            position: { x: 483.2352941176471, y: 528.4313725490196 },
            rotation: 0,
            parentId: null,
            offset: { x: 211.23529411764707, y: 207.43137254901956 },
        },
        {
            id: "bathtub-1",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/bathtub-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "bathtub",
                label: "浴室1-浸浴1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/bathtub.png",
                size: { width: 120, height: 60 },
            },
            size: { width: 70, height: 35 },
            position: { x: 489.82352941176464, y: 357.92156862745094 },
            rotation: 0,
            parentId: null,
            offset: { x: 219.82352941176464, y: 52.92156862745094 },
        },
        {
            id: "sink-1",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/sink-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "sink",
                label: "浴室1-锌盘1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/sink.png",
                size: { width: 60, height: 40 },
            },
            size: { width: 60, height: 40 },
            position: { x: 291.92156862745094, y: 481.11764705882354 },
            rotation: -270,
            parentId: null,
            offset: { x: -5.078431372549062, y: 153.11764705882354 },
        },
        {
            id: "door-1",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/door-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "door",
                label: "浴室1-門1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/door.png",
                size: { width: 40, height: 40 },
            },
            size: { width: 40, height: 40 },
            position: { x: 417.3137254901961, y: 572.4117647058823 },
            rotation: -90,
            parentId: null,
        },
        {
            id: "window-1",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/window-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "window",
                label: "浴室1-窗2",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/window.png",
                size: { width: 8, height: 56 },
            },
            size: { width: 8, height: 56 },
            position: { x: 310.72549019607845, y: 362.7254901960784 },
            rotation: -180,
            parentId: null,
        },
        {
            id: "door-2",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/door-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "door",
                label: "飯廳1-門1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/door.png",
                size: { width: 40, height: 40 },
            },
            size: { width: 40, height: 40 },
            position: { x: 160.37254901960785, y: 755.2156862745098 },
            rotation: 0,
            parentId: "dining_room-1",
            offset: { x: 4.529411764705969, y: 131.33333333333337 },
        },
        {
            id: "window-2",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/window-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "window",
                label: "浴室1-窗1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/window.png",
                size: { width: 8, height: 56 },
            },
            size: { width: 8, height: 56 },
            position: { x: 240.58823529411762, y: 622.4901960784314 },
            rotation: -90,
            parentId: "dining_room-1",
            offset: { x: 91.74509803921575, y: -20.392156862745082 },
        },
        {
            id: "table-1",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/table-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "table",
                label: "飯廳1-枱1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/table.png",
                size: { width: 44, height: 120 },
            },
            size: { width: 44, height: 120 },
            position: { x: 290.37254901960785, y: 657.5294117647059 },
            rotation: -90,
            parentId: "dining_room-1",
            offset: { x: 100.52941176470597, y: 9.647058823529392 },
        },
        {
            id: "fridge-1",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/fridge-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "fridge",
                label: "廚房1-冰箱1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/fridge.png",
                size: { width: 40, height: 43 },
            },
            size: { width: 40, height: 43 },
            position: { x: 339.2941176470588, y: 991.6666666666667 },
            rotation: 0,
            parentId: null,
        },
        {
            id: "door-3",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/door-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "door",
                label: "廚房1-門1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/door.png",
                size: { width: 40, height: 40 },
            },
            size: { width: 40, height: 40 },
            position: { x: 433.4509803921569, y: 943.5686274509803 },
            rotation: -270,
            parentId: null,
        },
        {
            id: "wardrobe-1",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/wardrobe-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "wardrobe",
                label: "飯廳1-櫃1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/wardrobe.png",
                size: { width: 40, height: 129 },
            },
            size: { width: 40, height: 129 },
            position: { x: 307.921568627451, y: 809.0588235294117 },
            rotation: -90,
            parentId: "dining_room-1",
            offset: { x: 166.07843137254912, y: 203.17647058823525 },
        },
        {
            id: "bed-1",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/bed-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "bed",
                label: "睡房2-床1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/bed.png",
                size: { width: 89, height: 128 },
            },
            size: { width: 89, height: 128 },
            position: { x: 861.6862745098039, y: 1134.078431372549 },
            rotation: -180,
            parentId: null,
        },
        {
            id: "window-3",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/window-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "window",
                label: "睡房2-窗1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/window.png",
                size: { width: 8, height: 56 },
            },
            size: { width: 8, height: 56 },
            position: { x: 702.5882352941177, y: 1253.313725490196 },
            rotation: -270,
            parentId: null,
        },
        {
            id: "window-4",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/window-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "window",
                label: "睡房2-窗2",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/window.png",
                size: { width: 8, height: 56 },
            },
            size: { width: 8, height: 56 },
            position: { x: 984.5490196078431, y: 1094.1372549019607 },
            rotation: 0,
            parentId: null,
        },
        {
            id: "bookshelf-1",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/bookshelf-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "bookshelf",
                label: "客廳1-茶几1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/bookshelf.png",
                size: { width: 44, height: 44 },
            },
            size: { width: 44, height: 44 },
            position: { x: 899.7058823529411, y: 748.9607843137255 },
            rotation: 0,
            parentId: null,
        },
        {
            id: "bed-2",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/bed-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "bed",
                label: "睡房1-床1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/bed.png",
                size: { width: 89, height: 128 },
            },
            size: { width: 89, height: 128 },
            position: { x: 781.7254901960785, y: 356.47058823529414 },
            rotation: 0,
            parentId: null,
        },
        {
            id: "stove-1",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/stove-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "stove",
                label: "廚房1-爐具1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/stove.png",
                size: { width: 62, height: 32 },
            },
            size: { width: 62, height: 32 },
            position: { x: 329.09803921568624, y: 1121.6470588235295 },
            rotation: -90,
            parentId: null,
        },
        {
            id: "sink-2",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/sink-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "sink",
                label: "廚房1-锌盘1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/sink.png",
                size: { width: 60, height: 40 },
            },
            size: { width: 60, height: 40 },
            position: { x: 420.6078431372549, y: 1231.1568627450981 },
            rotation: 0,
            parentId: null,
        },
        {
            id: "tv-1",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/tv-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "tv",
                label: "客廳1-電視1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/tv.png",
                size: { width: 134, height: 32 },
            },
            size: { width: 134, height: 32 },
            position: { x: 855.6078431372549, y: 658.9411764705882 },
            rotation: 0,
            parentId: null,
        },
        {
            id: "sofa-1",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/sofa-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "sofa",
                label: "客廳1-沙發1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/sofa.png",
                size: { width: 67, height: 123 },
            },
            size: { width: 67, height: 123 },
            position: { x: 891.5294117647059, y: 800.4901960784314 },
            rotation: -90,
            parentId: null,
        },

        {
            id: "door-4",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/door-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "door",
                label: "睡房2-門1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/door.png",
                size: { width: 40, height: 40 },
            },
            size: { width: 40, height: 40 },
            position: { x: 754.2549019607843, y: 944.8431372549019 },
            rotation: -270,
            parentId: null,
        },
        {
            id: "door-5",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/door-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "door",
                label: "睡房1-門1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/door.png",
                size: { width: 40, height: 40 },
            },
            size: { width: 40, height: 40 },
            position: { x: 729.4117647058823, y: 568.9607843137255 },
            rotation: -90,
            parentId: null,
        },
        {
            id: "wardrobe-2",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/wardrobe-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "wardrobe",
                label: "睡房2-櫃1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/wardrobe.png",
                size: { width: 40, height: 129 },
            },
            size: { width: 40, height: 129 },
            position: { x: 623.2745098039215, y: 1063.6470588235295 },
            rotation: 0,
            parentId: null,
        },
        {
            id: "wardrobe-3",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/wardrobe-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "wardrobe",
                label: "睡房1-櫃1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/wardrobe.png",
                size: { width: 40, height: 129 },
            },
            size: { width: 40, height: 129 },
            position: { x: 614.3529411764706, y: 452.01960784313724 },
            rotation: 0,
            parentId: null,
        },
        {
            id: "window-5",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/window-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "window",
                label: "未分配-窗",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/window.png",
                size: { width: 8, height: 56 },
            },
            size: { width: 8, height: 56 },
            position: { x: 928.0196078431372, y: 455 },
            rotation: 0,
            parentId: null,
        },
        {
            id: "window-6",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/window-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "window",
                label: "廚房1-窗1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/window.png",
                size: { width: 8, height: 56 },
            },
            size: { width: 8, height: 56 },
            position: { x: 337.0588235294117, y: 1196.6666666666667 },
            rotation: 0,
            parentId: null,
        },
        {
            id: "wardrobe-4",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/wardrobe-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "wardrobe",
                label: "廚房1-櫃1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/wardrobe.png",
                size: { width: 40, height: 129 },
            },
            size: { width: 40, height: 129 },
            position: { x: 520.9411764705883, y: 1060.8431372549019 },
            rotation: 0,
            parentId: null,
        },
        {
            id: "table-2",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/table-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "table",
                label: "睡房2-枱1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/table.png",
                size: { width: 44, height: 120 },
            },
            size: { width: 44, height: 120 },
            position: { x: 706.5294117647059, y: 1171.392156862745 },
            rotation: -90,
            parentId: null,
        },
        {
            id: "chair-1",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/chair-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "chair",
                label: "飯廳1-椅子1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/chair.png",
                size: { width: 28, height: 35 },
            },
            size: { width: 28, height: 35 },
            position: { x: 267.3529411764706, y: 747.0196078431372 },
            rotation: -90,
            parentId: "dining_room-1",
            offset: { x: 75.50980392156873, y: 107.13725490196077 },
        },
        {
            id: "chair-2",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/chair-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "chair",
                label: "飯廳1-椅子3",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/chair.png",
                size: { width: 28, height: 35 },
            },
            size: { width: 28, height: 35 },
            position: { x: 328.5098039215686, y: 747.6078431372548 },
            rotation: -90,
            parentId: "dining_room-1",
            offset: { x: 139.66666666666674, y: 106.72549019607834 },
        },
        {
            id: "chair-3",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/chair-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "chair",
                label: "飯廳1-椅子2",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/chair.png",
                size: { width: 28, height: 35 },
            },
            size: { width: 28, height: 35 },
            position: { x: 265.43137254901956, y: 662.1764705882354 },
            rotation: -270,
            parentId: "dining_room-1",
            offset: { x: 77.58823529411768, y: 16.294117647058897 },
        },
        {
            id: "chair-4",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/chair-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "chair",
                label: "飯廳1-椅子4",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/chair.png",
                size: { width: 28, height: 35 },
            },
            size: { width: 28, height: 35 },
            position: { x: 325.52941176470586, y: 660.3529411764705 },
            rotation: -270,
            parentId: "dining_room-1",
            offset: { x: 136.68627450980398, y: 15.47058823529403 },
        },
        {
            id: "wardrobe-5",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/wardrobe-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "wardrobe",
                label: "客廳1-櫃1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/wardrobe.png",
                size: { width: 40, height: 129 },
            },
            size: { width: 40, height: 129 },
            position: { x: 653.9215686274509, y: 809.0392156862745 },
            rotation: -90,
            parentId: null,
        },
        {
            id: "tv-2",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/tv-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "tv",
                label: "睡房2-電視1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/tv.png",
                size: { width: 134, height: 32 },
            },
            size: { width: 134, height: 32 },
            position: { x: 850, y: 962.2352941176471 },
            rotation: 0,
            parentId: null,
        },
        {
            id: "plant-1",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/plant-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "plant",
                label: "陽台1-植物2",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/plant.png",
                size: { width: 36, height: 36 },
            },
            size: { width: 36, height: 36 },
            position: { x: 1057.2549019607843, y: 871.6078431372549 },
            rotation: 0,
            parentId: null,
        },
        {
            id: "plant-2",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/plant-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "plant",
                label: "陽台1-植物1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/plant.png",
                size: { width: 36, height: 36 },
            },
            size: { width: 36, height: 36 },
            position: { x: 1055.2549019607843, y: 650.9803921568628 },
            rotation: 0,
            parentId: null,
        },
        {
            id: "door-6",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/door-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "door",
                label: "陽台1-門1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/door.png",
                size: { width: 40, height: 40 },
            },
            size: { width: 40, height: 40 },
            position: { x: 1049.0819672131147, y: 769.6393442622951 },
            rotation: 0,
            parentId: null,
        },
    ]
}



export const LAYOUT1_ZH = {
    canvasPosition: { x: 0, y: -18 },
    compassRotation: 0,
    scale: 61,
    localItems: [
        {
            id: "bathroom-1",
            type: ITEM_TYPES.ROOM,
            data: {
                cateType: ITEM_TYPES.ROOM,
                type: "bathroom",
                label: "浴室1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/room-icon/bathroom.png",
                size: { width: 300, height: 300 },
            },
            size: { width: 300, height: 300 },
            position: { x: 284.47058823529414, y: 329.37254901960785 },
            rotation: 0,
        },
        {
            id: "dining_room-1",
            type: ITEM_TYPES.ROOM,
            data: {
                cateType: ITEM_TYPES.ROOM,
                type: "dining_room",
                label: "饭厅1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/room-icon/dining_room.png",
                size: { width: 300, height: 300 },
            },
            size: { width: 441, height: 296 },
            position: { x: 144.84313725490188, y: 632.8823529411765 },
            rotation: 0,
        },
        {
            id: "living_room-1",
            type: ITEM_TYPES.ROOM,
            data: {
                cateType: ITEM_TYPES.ROOM,
                type: "living_room",
                label: "客厅1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/room-icon/living_room.png",
                size: { width: 300, height: 300 },
            },
            size: { width: 443, height: 290 },
            position: { x: 588.1176470588235, y: 634.4509803921569 },
            rotation: 0,
        },
        {
            id: "bedroom-1",
            type: ITEM_TYPES.ROOM,
            data: {
                cateType: ITEM_TYPES.ROOM,
                type: "bedroom",
                label: "睡房1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/room-icon/bedroom.png",
                size: { width: 300, height: 300 },
            },
            size: { width: 367, height: 304 },
            position: { x: 589.5882352941177, y: 330.78431372549016 },
            rotation: 0,
        },
        {
            id: "bedroom-2",
            type: ITEM_TYPES.ROOM,
            data: {
                cateType: ITEM_TYPES.ROOM,
                type: "bedroom",
                label: "睡房2",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/room-icon/bedroom.png",
                size: { width: 300, height: 300 },
            },
            size: { width: 421, height: 375 },
            position: { x: 593.3529411764706, y: 926.4705882352941 },
            rotation: 0,
        },
        {
            id: "kitchen-1",
            type: ITEM_TYPES.ROOM,
            data: {
                cateType: ITEM_TYPES.ROOM,
                type: "kitchen",
                label: "厨房1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/room-icon/kitchen.png",
                size: { width: 300, height: 300 },
            },
            size: { width: 270, height: 363 },
            position: { x: 315.0392156862745, y: 930.4509803921569 },
            rotation: 0,
        },
        {
            id: "balcony-1",
            type: ITEM_TYPES.ROOM,
            data: {
                cateType: ITEM_TYPES.ROOM,
                type: "balcony",
                label: "阳台1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/room-icon/balcony.png",
                size: { width: 300, height: 300 },
            },
            size: { width: 116, height: 296 },
            position: { x: 1030.764705882353, y: 635.8039215686274 },
            rotation: 0,
        },
        // --- Furniture ---
        {
            id: "toilet-1",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/toilet-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "toilet",
                label: "浴室1-马桶1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/toilet.png",
                size: { width: 40, height: 60 },
            },
            size: { width: 40, height: 60 },
            position: { x: 410.843137254902, y: 351.5490196078431 },
            rotation: 0,
            parentId: null,
            offset: { x: 134.843137254902, y: 7.549019607843093 },
        },
        {
            id: "shower-1",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/shower-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "shower",
                label: "浴室1-淋浴1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/shower.png",
                size: { width: 80, height: 80 },
            },
            size: { width: 80, height: 80 },
            position: { x: 483.2352941176471, y: 528.4313725490196 },
            rotation: 0,
            parentId: null,
            offset: { x: 211.23529411764707, y: 207.43137254901956 },
        },
        {
            id: "bathtub-1",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/bathtub-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "bathtub",
                label: "浴室1-浸浴1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/bathtub.png",
                size: { width: 120, height: 60 },
            },
            size: { width: 70, height: 35 },
            position: { x: 489.82352941176464, y: 357.92156862745094 },
            rotation: 0,
            parentId: null,
            offset: { x: 219.82352941176464, y: 52.92156862745094 },
        },
        {
            id: "sink-1",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/sink-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "sink",
                label: "浴室1-锌盘1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/sink.png",
                size: { width: 60, height: 40 },
            },
            size: { width: 60, height: 40 },
            position: { x: 291.92156862745094, y: 481.11764705882354 },
            rotation: -270,
            parentId: null,
            offset: { x: -5.078431372549062, y: 153.11764705882354 },
        },
        {
            id: "door-1",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/door-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "door",
                label: "浴室1-门1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/door.png",
                size: { width: 40, height: 40 },
            },
            size: { width: 40, height: 40 },
            position: { x: 417.3137254901961, y: 572.4117647058823 },
            rotation: -90,
            parentId: null,
        },
        {
            id: "window-1",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/window-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "window",
                label: "浴室1-窗2",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/window.png",
                size: { width: 8, height: 56 },
            },
            size: { width: 8, height: 56 },
            position: { x: 310.72549019607845, y: 362.7254901960784 },
            rotation: -180,
            parentId: null,
        },
        {
            id: "door-2",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/door-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "door",
                label: "饭厅1-门1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/door.png",
                size: { width: 40, height: 40 },
            },
            size: { width: 40, height: 40 },
            position: { x: 160.37254901960785, y: 755.2156862745098 },
            rotation: 0,
            parentId: "dining_room-1",
            offset: { x: 4.529411764705969, y: 131.33333333333337 },
        },
        {
            id: "window-2",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/window-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "window",
                label: "浴室1-窗1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/window.png",
                size: { width: 8, height: 56 },
            },
            size: { width: 8, height: 56 },
            position: { x: 240.58823529411762, y: 622.4901960784314 },
            rotation: -90,
            parentId: "dining_room-1",
            offset: { x: 91.74509803921575, y: -20.392156862745082 },
        },
        {
            id: "table-1",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/table-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "table",
                label: "饭厅1-枱1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/table.png",
                size: { width: 44, height: 120 },
            },
            size: { width: 44, height: 120 },
            position: { x: 290.37254901960785, y: 657.5294117647059 },
            rotation: -90,
            parentId: "dining_room-1",
            offset: { x: 100.52941176470597, y: 9.647058823529392 },
        },
        {
            id: "fridge-1",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/fridge-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "fridge",
                label: "厨房1-冰箱1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/fridge.png",
                size: { width: 40, height: 43 },
            },
            size: { width: 40, height: 43 },
            position: { x: 339.2941176470588, y: 991.6666666666667 },
            rotation: 0,
            parentId: null,
        },
        {
            id: "door-3",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/door-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "door",
                label: "厨房1-门1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/door.png",
                size: { width: 40, height: 40 },
            },
            size: { width: 40, height: 40 },
            position: { x: 433.4509803921569, y: 943.5686274509803 },
            rotation: -270,
            parentId: null,
        },
        {
            id: "wardrobe-1",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/wardrobe-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "wardrobe",
                label: "饭厅1-柜1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/wardrobe.png",
                size: { width: 40, height: 129 },
            },
            size: { width: 40, height: 129 },
            position: { x: 307.921568627451, y: 809.0588235294117 },
            rotation: -90,
            parentId: "dining_room-1",
            offset: { x: 166.07843137254912, y: 203.17647058823525 },
        },
        {
            id: "bed-1",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/bed-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "bed",
                label: "睡房2-床1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/bed.png",
                size: { width: 89, height: 128 },
            },
            size: { width: 89, height: 128 },
            position: { x: 861.6862745098039, y: 1134.078431372549 },
            rotation: -180,
            parentId: null,
        },
        {
            id: "window-3",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/window-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "window",
                label: "睡房2-窗1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/window.png",
                size: { width: 8, height: 56 },
            },
            size: { width: 8, height: 56 },
            position: { x: 702.5882352941177, y: 1253.313725490196 },
            rotation: -270,
            parentId: null,
        },
        {
            id: "window-4",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/window-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "window",
                label: "睡房2-窗2",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/window.png",
                size: { width: 8, height: 56 },
            },
            size: { width: 8, height: 56 },
            position: { x: 984.5490196078431, y: 1094.1372549019607 },
            rotation: 0,
            parentId: null,
        },
        {
            id: "bookshelf-1",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/bookshelf-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "bookshelf",
                label: "客厅1-茶几1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/bookshelf.png",
                size: { width: 44, height: 44 },
            },
            size: { width: 44, height: 44 },
            position: { x: 899.7058823529411, y: 748.9607843137255 },
            rotation: 0,
            parentId: null,
        },
        {
            id: "bed-2",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/bed-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "bed",
                label: "睡房1-床1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/bed.png",
                size: { width: 89, height: 128 },
            },
            size: { width: 89, height: 128 },
            position: { x: 781.7254901960785, y: 356.47058823529414 },
            rotation: 0,
            parentId: null,
        },
        {
            id: "stove-1",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/stove-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "stove",
                label: "厨房1-炉具1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/stove.png",
                size: { width: 62, height: 32 },
            },
            size: { width: 62, height: 32 },
            position: { x: 329.09803921568624, y: 1121.6470588235295 },
            rotation: -90,
            parentId: null,
        },
        {
            id: "sink-2",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/sink-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "sink",
                label: "厨房1-锌盘1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/sink.png",
                size: { width: 60, height: 40 },
            },
            size: { width: 60, height: 40 },
            position: { x: 420.6078431372549, y: 1231.1568627450981 },
            rotation: 0,
            parentId: null,
        },
        {
            id: "tv-1",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/tv-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "tv",
                label: "客厅1-电视1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/tv.png",
                size: { width: 134, height: 32 },
            },
            size: { width: 134, height: 32 },
            position: { x: 855.6078431372549, y: 658.9411764705882 },
            rotation: 0,
            parentId: null,
        },
        {
            id: "sofa-1",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/sofa-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "sofa",
                label: "客厅1-沙发1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/sofa.png",
                size: { width: 67, height: 123 },
            },
            size: { width: 67, height: 123 },
            position: { x: 891.5294117647059, y: 800.4901960784314 },
            rotation: -90,
            parentId: null,
        },

        {
            id: "door-4",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/door-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "door",
                label: "睡房2-门1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/door.png",
                size: { width: 40, height: 40 },
            },
            size: { width: 40, height: 40 },
            position: { x: 754.2549019607843, y: 944.8431372549019 },
            rotation: -270,
            parentId: null,
        },
        {
            id: "door-5",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/door-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "door",
                label: "睡房1-门1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/door.png",
                size: { width: 40, height: 40 },
            },
            size: { width: 40, height: 40 },
            position: { x: 729.4117647058823, y: 568.9607843137255 },
            rotation: -90,
            parentId: null,
        },
        {
            id: "wardrobe-2",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/wardrobe-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "wardrobe",
                label: "睡房2-柜1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/wardrobe.png",
                size: { width: 40, height: 129 },
            },
            size: { width: 40, height: 129 },
            position: { x: 623.2745098039215, y: 1063.6470588235295 },
            rotation: 0,
            parentId: null,
        },
        {
            id: "wardrobe-3",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/wardrobe-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "wardrobe",
                label: "睡房1-柜1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/wardrobe.png",
                size: { width: 40, height: 129 },
            },
            size: { width: 40, height: 129 },
            position: { x: 614.3529411764706, y: 452.01960784313724 },
            rotation: 0,
            parentId: null,
        },
        {
            id: "window-5",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/window-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "window",
                label: "未分配-窗",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/window.png",
                size: { width: 8, height: 56 },
            },
            size: { width: 8, height: 56 },
            position: { x: 928.0196078431372, y: 455 },
            rotation: 0,
            parentId: null,
        },
        {
            id: "window-6",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/window-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "window",
                label: "厨房1-窗1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/window.png",
                size: { width: 8, height: 56 },
            },
            size: { width: 8, height: 56 },
            position: { x: 337.0588235294117, y: 1196.6666666666667 },
            rotation: 0,
            parentId: null,
        },
        {
            id: "wardrobe-4",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/wardrobe-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "wardrobe",
                label: "厨房1-柜1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/wardrobe.png",
                size: { width: 40, height: 129 },
            },
            size: { width: 40, height: 129 },
            position: { x: 520.9411764705883, y: 1060.8431372549019 },
            rotation: 0,
            parentId: null,
        },
        {
            id: "table-2",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/table-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "table",
                label: "睡房2-枱1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/table.png",
                size: { width: 44, height: 120 },
            },
            size: { width: 44, height: 120 },
            position: { x: 706.5294117647059, y: 1171.392156862745 },
            rotation: -90,
            parentId: null,
        },
        {
            id: "chair-1",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/chair-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "chair",
                label: "饭厅1-椅子1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/chair.png",
                size: { width: 28, height: 35 },
            },
            size: { width: 28, height: 35 },
            position: { x: 267.3529411764706, y: 747.0196078431372 },
            rotation: -90,
            parentId: "dining_room-1",
            offset: { x: 75.50980392156873, y: 107.13725490196077 },
        },
        {
            id: "chair-2",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/chair-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "chair",
                label: "饭厅1-椅子3",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/chair.png",
                size: { width: 28, height: 35 },
            },
            size: { width: 28, height: 35 },
            position: { x: 328.5098039215686, y: 747.6078431372548 },
            rotation: -90,
            parentId: "dining_room-1",
            offset: { x: 139.66666666666674, y: 106.72549019607834 },
        },
        {
            id: "chair-3",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/chair-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "chair",
                label: "饭厅1-椅子2",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/chair.png",
                size: { width: 28, height: 35 },
            },
            size: { width: 28, height: 35 },
            position: { x: 265.43137254901956, y: 662.1764705882354 },
            rotation: -270,
            parentId: "dining_room-1",
            offset: { x: 77.58823529411768, y: 16.294117647058897 },
        },
        {
            id: "chair-4",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/chair-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "chair",
                label: "饭厅1-椅子4",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/chair.png",
                size: { width: 28, height: 35 },
            },
            size: { width: 28, height: 35 },
            position: { x: 325.52941176470586, y: 660.3529411764705 },
            rotation: -270,
            parentId: "dining_room-1",
            offset: { x: 136.68627450980398, y: 15.47058823529403 },
        },
        {
            id: "wardrobe-5",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/wardrobe-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "wardrobe",
                label: "客厅1-柜1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/wardrobe.png",
                size: { width: 40, height: 129 },
            },
            size: { width: 40, height: 129 },
            position: { x: 653.9215686274509, y: 809.0392156862745 },
            rotation: -90,
            parentId: null,
        },
        {
            id: "tv-2",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/tv-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "tv",
                label: "睡房2-电视1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/tv.png",
                size: { width: 134, height: 32 },
            },
            size: { width: 134, height: 32 },
            position: { x: 850, y: 962.2352941176471 },
            rotation: 0,
            parentId: null,
        },
        {
            id: "plant-1",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/plant-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "plant",
                label: "阳台1-植物2",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/plant.png",
                size: { width: 36, height: 36 },
            },
            size: { width: 36, height: 36 },
            position: { x: 1057.2549019607843, y: 871.6078431372549 },
            rotation: 0,
            parentId: null,
        },
        {
            id: "plant-2",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/plant-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "plant",
                label: "阳台1-植物1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/plant.png",
                size: { width: 36, height: 36 },
            },
            size: { width: 36, height: 36 },
            position: { x: 1055.2549019607843, y: 650.9803921568628 },
            rotation: 0,
            parentId: null,
        },
        {
            id: "door-6",
            type: ITEM_TYPES.FURNITURE,
            activeIcon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/door-gr.png",
            data: {
                cateType: ITEM_TYPES.FURNITURE,
                type: "door",
                label: "阳台1-门1",
                icon: "https://d3cbeloe0vn1bb.cloudfront.net/images/fur-icon/door.png",
                size: { width: 40, height: 40 },
            },
            size: { width: 40, height: 40 },
            position: { x: 1049.0819672131147, y: 769.6393442622951 },
            rotation: 0,
            parentId: null,
        },
    ]
}